name: tf
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - arrow-cpp=11.0.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - bokeh=3.1.1
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cloudpickle=2.2.1
  - cuda-nvcc=11.3.58
  - cudatoolkit=11.2.0
  - cudnn=8.1.0.77
  - cytoolz=0.12.0
  - dask=2023.6.0
  - dask-core=2023.6.0
  - distributed=2023.6.0
  - faiss=1.7.4
  - faiss-cpu=1.7.4
  - freetype=2.12.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - heapdict=1.0.1
  - icu=58.2
  - jinja2=3.1.2
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - msgpack-python=1.0.3
  - ncurses=6.4
  - numexpr=2.8.4
  - openssl=3.0.9
  - orc=1.7.4
  - partd=1.2.0
  - pip=23.0.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-lmdb=1.4.1
  - python_abi=3.9
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - tblib=1.7.0
  - tk=8.6.12
  - toolz=0.12.0
  - tzdata=2023c
  - utf8proc=2.6.1
  - wheel=0.38.4
  - xyzservices=2022.9.0
  - xz=5.4.2
  - yaml=0.2.5
  - zict=2.2.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - aiobotocore==2.5.2
      - aiohttp==3.8.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - anyio==3.7.1
      - apache-beam==2.46.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - botocore==1.29.161
      - cachetools==4.2.4
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - comm==0.1.3
      - contourpy==1.1.0
      - crcmod==1.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.1.1
      - dm-tree==0.1.8
      - docopt==0.6.2
      - etils==1.2.0
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - fastavro==1.7.3
      - fasteners==0.18
      - fastjsonschema==2.17.1
      - flatbuffers==23.5.26
      - fonttools==4.41.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gast==0.4.0
      - google-api-core==2.11.0
      - google-api-python-client==1.12.11
      - google-apitools==0.5.31
      - google-auth==2.17.3
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-aiplatform==1.21.0
      - google-cloud-bigquery==3.10.0
      - google-cloud-bigquery-storage==2.16.2
      - google-cloud-bigtable==1.7.3
      - google-cloud-core==2.3.2
      - google-cloud-datastore==1.15.5
      - google-cloud-dlp==3.12.1
      - google-cloud-language==1.3.2
      - google-cloud-pubsub==2.16.0
      - google-cloud-pubsublite==1.8.1
      - google-cloud-recommendations-ai==0.7.1
      - google-cloud-resource-manager==1.10.0
      - google-cloud-spanner==3.32.0
      - google-cloud-storage==2.8.0
      - google-cloud-videointelligence==1.16.3
      - google-cloud-vision==3.4.1
      - google-crc32c==1.5.0
      - google-pasta==0.2.0
      - google-resumable-media==2.5.0
      - googleapis-common-protos==1.59.0
      - grpc-google-iam-v1==0.12.6
      - grpcio==1.54.0
      - grpcio-status==1.48.2
      - gviz-api==1.10.0
      - h5py==3.8.0
      - hdfs==2.7.0
      - httplib2==0.21.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - ipykernel==6.24.0
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jmespath==1.0.1
      - joblib==0.14.1
      - jsonpointer==2.4
      - jsonschema==4.18.3
      - jsonschema-specifications==2023.6.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.6.3
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - keras==2.11.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - multidict==6.0.4
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.6.0
      - nbformat==5.9.1
      - nest-asyncio==1.5.6
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.0.131
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - objsize==0.6.1
      - opt-einsum==3.3.0
      - orjson==3.8.11
      - overrides==6.5.0
      - packaging==21.3
      - pandas==1.5.3
      - pandas-tfrecords==0.1.6
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - proto-plus==1.22.2
      - protobuf==3.19.6
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==5.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydot==1.4.2
      - pyfarmhash==0.3.2
      - pygments==2.15.1
      - pymongo==3.13.0
      - pyparsing==3.0.9
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyzmq==25.1.0
      - referencing==0.29.1
      - regex==2023.3.23
      - requests==2.29.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.8.10
      - rsa==4.9
      - s3fs==2023.6.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - shapely==1.8.5.post1
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlparse==0.4.4
      - stack-data==0.6.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-profile==2.8.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-data-validation==1.9.0
      - tensorflow-datasets==4.8.2
      - tensorflow-estimator==2.11.0
      - tensorflow-gpu==2.11.0
      - tensorflow-hub==0.14.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - tensorflow-metadata==1.9.0
      - tensorflow-recommenders==0.7.3
      - tensorflow-serving-api==2.9.0
      - tensorflow-text==2.11.0
      - tensorrt==8.5.3.1
      - termcolor==2.3.0
      - terminado==0.17.1
      - tfx-bsl==1.9.0
      - tinycss2==1.2.1
      - toml==0.10.2
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typing-extensions==4.5.0
      - uri-template==1.3.0
      - uritemplate==3.0.1
      - urllib3==1.26.15
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.0.3
      - wrapt==1.15.0
      - yarl==1.9.2
      - zipp==3.15.0
      - zstandard==0.21.0
