name: tf
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2023.5.7
  - cuda-nvcc=11.3.58
  - cudatoolkit=11.2.0
  - cudnn=8.1.0.77
  - faiss=1.7.4
  - faiss-cpu=1.7.4
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.23
  - libstdcxx-ng=13.1.0
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - openssl=3.1.1
  - pip=23.0.1
  - python=3.9.16
  - python_abi=3.9
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - apache-beam==2.46.0
      - astunparse==1.6.3
      - cachetools==4.2.4
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - crcmod==1.7
      - dill==0.3.1.1
      - dm-tree==0.1.8
      - docopt==0.6.2
      - etils==1.2.0
      - fastavro==1.7.3
      - fasteners==0.18
      - flatbuffers==23.3.3
      - gast==0.4.0
      - google-api-core==2.11.0
      - google-api-python-client==1.12.11
      - google-apitools==0.5.31
      - google-auth==2.17.3
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-aiplatform==1.21.0
      - google-cloud-bigquery==3.10.0
      - google-cloud-bigquery-storage==2.16.2
      - google-cloud-bigtable==1.7.3
      - google-cloud-core==2.3.2
      - google-cloud-datastore==1.15.5
      - google-cloud-dlp==3.12.1
      - google-cloud-language==1.3.2
      - google-cloud-pubsub==2.16.0
      - google-cloud-pubsublite==1.8.1
      - google-cloud-recommendations-ai==0.7.1
      - google-cloud-resource-manager==1.10.0
      - google-cloud-spanner==3.32.0
      - google-cloud-storage==2.8.0
      - google-cloud-videointelligence==1.16.3
      - google-cloud-vision==3.4.1
      - google-crc32c==1.5.0
      - google-pasta==0.2.0
      - google-resumable-media==2.5.0
      - googleapis-common-protos==1.59.0
      - grpc-google-iam-v1==0.12.6
      - grpcio==1.54.0
      - grpcio-status==1.48.2
      - gviz-api==1.10.0
      - h5py==3.8.0
      - hdfs==2.7.0
      - httplib2==0.21.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - keras==2.11.0
      - libclang==16.0.0
      - markdown==3.4.3
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.0.131
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - objsize==0.6.1
      - opt-einsum==3.3.0
      - orjson==3.8.11
      - overrides==6.5.0
      - packaging==21.3
      - pandas==1.5.3
      - promise==2.3
      - proto-plus==1.22.2
      - protobuf==3.19.6
      - psutil==5.9.5
      - pyarrow==6.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydot==1.4.2
      - pyfarmhash==0.3.2
      - pymongo==3.13.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.3.23
      - requests==2.29.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - shapely==1.8.5.post1
      - six==1.16.0
      - sqlparse==0.4.4
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-profile==2.11.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-data-validation==1.12.0
      - tensorflow-datasets==4.8.2
      - tensorflow-estimator==2.11.0
      - tensorflow-gpu==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - tensorflow-metadata==1.12.0
      - tensorflow-recommenders==0.7.3
      - tensorflow-serving-api==2.11.0
      - tensorrt==8.5.3.1
      - termcolor==2.3.0
      - tfx-bsl==1.12.0
      - toml==0.10.2
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - uritemplate==3.0.1
      - urllib3==1.26.15
      - werkzeug==2.0.3
      - wrapt==1.15.0
      - zipp==3.15.0
      - zstandard==0.21.0
