model:
  ranker: MaskCN
  ranking_emb: CriteoRankingEmb
  label: label
  layer_sizes: "400,400,400"
  cross_layer_nums: "1,1,1"
  mask_block_dim: 64

train:
  task_name: RankerTrain
  epochs: 1
  batch_size: 512
  learning_rate: 0.0001
  train_data: criteo/train/7_days_train_samples
  test_data: criteo/train/day_7_sample_small
  meta_data: trainer/meta/criteo.json
  model_dir: trainer/saved_models/criteo_ranker
  log_dir: logs
