model:
  ranker: AutoInt
  ranking_emb: CriteoDenseAsWeightRankingEmb
  label: label
  att_layer_num: 3
  head_dim: 32
  head_num: 2
  dnn_layer_sizes: "512,256"

train:
  task_name: RankerTrain
  epochs: 1
  batch_size: 512
  learning_rate: 0.0001
  train_data: criteo/train/7_days_train_samples
  test_data: criteo/train/day_7_sample_small
  meta_data: trainer/meta/criteo.json
  model_dir: trainer/saved_models/criteo_ranker
  log_dir: logs
