model:
  ranker: MaskNet
  ranking_emb: CriteoRankingEmb
  label: label
  layer_sizes: "400,400,400"
  mask_block_dim: 256
  mode: parallel
  mask_block_num: 3
  reduction_ratio: 2

train:
  task_name: RankerTrain
  epochs: 1
  batch_size: 512
  learning_rate: 0.0001
  train_data: criteo/train/7_days_train_samples
  test_data: criteo/train/day_7_sample_small
  meta_data: trainer/meta/criteo.json
  model_dir: trainer/saved_models/criteo_ranker
  log_dir: logs
