model:
  ranker: DeepCrossNetworkV2
  ranking_emb: CriteoRankingEmb
  layer_sizes: "512,512"
  layer_num: 3
  mode: parallel
  label: label
  cross_net: gating_mix
  expert_num: 4
  gate_func: sigmoid
  activation: tanh

train:
  task_name: RankerTrain
  epochs: 1
  batch_size: 512
  learning_rate: 0.0001
  train_data: criteo/train/7_days_train_samples
  test_data: criteo/train/day_7_sample_small
  meta_data: trainer/meta/criteo.json
  model_dir: trainer/saved_models/criteo_ranker
  log_dir: logs