model:
  ranker: xDeepFM
  ranking_emb: "MovieLensDeepFMDeepEmb, MovieLensDeepFMWideEmb"
  label: user_rating
  layer_sizes: "100,100,100"
  split_half: true
  cin_activation: linear

train:
  task_name: RankerTrain
  epochs: 3
  batch_size: 256
  learning_rate: 0.001
  train_data: movielens/data/ratings_train_remove_rating3
  test_data: movielens/data/ratings_test_remove_rating3
  meta_data: trainer/meta/movie_lens.json
  model_dir: trainer/saved_models/movielens_ranker
  log_dir: logs
