model:
  ranker: "MaskNet"
  ranking_emb: "MovieLensRankingEmb"
  label: "user_rating"
  mask_block_dim: 64
  mode: "parallel"
  mask_block_num: 5
  reduction_ratio: 2

train:
  task_name: "RankerTrain"
  epochs: 1
  batch_size: 256
  learning_rate: 0.001
  train_data: "movielens/data/ratings_train_ranker"
  test_data: "movielens/data/ratings_test_ranker"
  meta_data: "trainer/meta/movie_lens.json"
  model_dir: "trainer/saved_models/movielens_ranker"
  log_dir: "logs"
