model:
  ranker: BasicRanker
  ranking_emb: MovieLensModel
  label: user_rating

train:
  task_name: RankerTrain
  epochs: 1
  batch_size: 256
  learning_rate: 0.001
  train_data: movielens/data/ratings_train_ranker
  test_data: movielens/data/ratings_test_ranker
  meta_data: trainer/meta/movie_lens.json
  model_dir: trainer/saved_models/movielens_ranker
  log_dir: logs
